### Create confirm token
POST http://localhost:3003/api/v1/confirmation/create
Content-Type: application/json

{
    "userId": "12333"
}


### Confirm user mail
POST http://localhost:3003/api/v1/confirmation
Content-Type: application/json

{
    "userId": "67cc28ba1dd17c18a1b9fe99",
    "token": "f0ed48d7-c1d6-46fd-af6c-cfe4ae993653"
}
