### Send POST request with json body
POST http://localhost:3001/api/v1/comments/add
Content-Type: application/json

{
    "text": "this is new awesome comment",
    "userId": "67c1c5f060c781d3640416ce",
    "postId": "d6e9110b-31a8-4229-a895-1b3e3b318cb5"
}
